export const tokenId = "token id";
export const tokenStandard = "token standard";
export const contractAddress = "contract address";
export const erc721 = "ERC721";
export const createNewNft = "create a new NFT";
export const nftId = "NFT id";
export const topUp = "top up";
export const creditTopUp = "credit top up";
export const topUpModalInfo = "enter the amount of tokens you would like to add to your account";
